version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "autopilot-churnprediction"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1ccv3bxpvfoxm"
s3_prefix = "autopilot-churnprediction"
region = "ap-southeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
